name: daejeon_bakery_app
description: 대전 빵집 지도 앱
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.5.0
  http: ^1.1.0
  intl: ^0.18.1
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  url_launcher: ^6.2.0
  geolocator: ^13.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/대전 빵사대 로고.png"
  min_sdk_android: 21
  background_color: "#4A2010"
  remove_alpha_ios: true
  adaptive_icon_background: "#4A2010"
  adaptive_icon_foreground: "assets/대전 빵사대 로고.png"

flutter:
  uses-material-design: true
  assets:
    - assets/